apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server-container
        image: gcr.io/nimble-courier-304504/server-gRPC
        ports:
        - containerPort: 50051