apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client-container
        image: gcr.io/nimble-courier-304504/client-gRPC
        ports:
        - containerPort: 10000